name: Build

on:
  push:
    branches:
      - "**"
  # workflow_dispatch:
  workflow_call:
    inputs:
      variant:
        description: 'Build variant'
        required: true
        default: '-debug'
        type: string
    secrets:
      GH_APP1_KEY:
        description: 'GitHub App private key'
        required: true

env:
  GH_APP1_ID: ${{ vars.GH_APP1_ID }}
  GH_APP1_KEY: ${{ secrets.GH_APP1_KEY }}

jobs:
  build-debug:
    runs-on: ubuntu-latest

    steps:
      - name: directly from vars and secrets
        run: |
          echo "GH_APP1_ID: ${{ vars.GH_APP1_ID }}" | rev
          echo "GH_APP1_KEY: ${{ secrets.GH_APP1_KEY }}" | rev

      - name: from environment variables
        run: |
          echo "GH_APP1_ID: $GH_APP1_ID " | rev
          echo "GH_APP1_KEY: $GH_APP1_KEY" | rev       
        env:
          GH_APP1_ID: ${{ vars.GH_APP1_ID }}
          GH_APP1_KEY: ${{ secrets.GH_APP1_KEY }}
      
      # - uses: actions/create-github-app-token@v1
      #   id: app-token
      #   with:
      #     app-id: ${{ vars.GH_APP1_ID }}
      #     private-key: ${{ secrets.GH_APP1_KEY }}
      #     owner: ${{ github.repository_owner }}

      # - name: Configure Git Authentication
      #   run: |
      #     echo ${{ steps.app-token.outputs.token }} | rev
      #     git config --global url."https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/mamn".insteadOf "https://github.com/mamn"
      #     git config --global user.email "dxp-build@electrolux.com"
      #     git config --global user.name "Electrolux Build"


      # - name: printenv
      #   run: |
      #     pwd
      #     ls
      #     python --version
      #     pip3 list


      # - name: Checkout repository
      #   run: |
      #     #git clone https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/mamn/repo2  
      #     git clone https://github.com/mamn/repo2

      #     cd ovcx_evo
      #     git branch
      #     git log -1

      # - name: Clean
      #   run: |
      #     cd ovcx_evo/Tools/Utilities
      #     ./build.bat c Debug

      # - name: Build
      #   run: |
      #     cd ovcx_evo/Tools/Utilities
      #     ./build.bat rb Debug

      # - name: List build output
      #   run: |
      #     cd ovcx_evo/Debug
      #     Dir -Recurse  | Select Fullname
